### ISSUE TITLE
Develop image slider view and photo gallery functionality

### ISSUE THREAD

**Issue by yurkiss** [ITsvetkoFF/Kv-009#12]
###### Tasks to do:
- [x] view small pictures in problem details layout
  - [x] display GridView with thumbnails
- [x] image pager view of problem's photos
  - [x] sliding image views
  - [x] zooming image
  - [x] hide/show action bar by tap on image
- [ ] add new photo button and selecting picture functionality
  - [ ] make up add new photo logic
- [x] AcyncTask fetch photos URLs by problem id

:camel::camel::camel:
